# erreur

Un outil [Sumor Cloud](https://sumor.cloud).  
[Plus de documentation](https://sumor.cloud)
Une bibliothèque de gestion des erreurs prenant en charge le multilingue, le code d'erreur prédéfini et le passage de données.

[![CI](https://github.com/sumor-cloud/error/actions/workflows/ci.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ci.yml)
[![Test](https://github.com/sumor-cloud/error/actions/workflows/ut.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ut.yml)
[![Couverture](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml)
[![Audit](https://github.com/sumor-cloud/error/actions/workflows/audit.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/audit.yml)

## Installation

```bash
npm i @sumor/error --save
```

## Prérequis

### Version de Node.JS

Nécessite Node.JS version 16.x ou supérieure

### Module ES de Node.JS requis

Comme ce package est écrit en module ES, veuillez modifier le code suivant dans votre fichier `package.json`:

```json
{
  "type": "module"
}
```

## Utilisation

### Définir une erreur

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    USER_NOT_FOUND: 'Utilisateur non trouvé',
    USER_EXISTED: 'L'utilisateur {name} existe'
  }
})

throw new MyError('USER_NOT_FOUND')
// sortie: Error: Utilisateur non trouvé

throw new MyError('USER_EXISTED', { name: 'Alice' })
// sortie: Error: L'utilisateur Alice existe
```

### Multi-langue

```js
import defineError from '@sumor/error'

const MyError = defineError({
  language: 'fr', // langue par défaut
  code: {
    USER_NOT_FOUND: 'Utilisateur non trouvé',
    USER_EXISTED: 'L'utilisateur {name} existe'
  },
  i18n: {
    zh: {
      USER_NOT_FOUND: 'Utilisateur non trouvé',
      USER_EXISTED: 'L'utilisateur {name} existe'
    }
  }
})

const error = new MyError('USER_EXISTED', { name: 'Alice' })
error.language = 'fr' // changer la langue de l'erreur
console.log(error)
// sortie: Error: L'utilisateur Alice existe

error.language = 'zh' // changer la langue de l'erreur
console.log(error)
// sortie: Error: L'utilisateur Alice existe
```

### Convertir l'erreur en JSON

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    USER_NOT_FOUND: 'Utilisateur non trouvé',
    USER_EXISTED: 'L'utilisateur {name} existe'
  }
})

const error = new MyError('USER_EXISTED', { name: 'Alice' })
console.log(error.json())
// sortie: {"code":"USER_EXISTED","message":"L'utilisateur Alice existe"}
```

### Erreur sous-jacente

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    FIELD_VERIFY_FAILED: 'Échec de la vérification du champ',
    FIELD_CANNOT_EMPTY: 'Le champ {name} ne peut pas être vide',
    FIELD_TOO_LONG: 'Le champ {name} est trop long'
  },
  i18n: {
    zh: {
      FIELD_VERIFY_FAILED: 'Échec de la vérification du champ',
      FIELD_CANNOT_EMPTY: 'Le champ {name} ne peut pas être vide',
      FIELD_TOO_LONG: 'Le champ {name} est trop long'
    }
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'nom d'utilisateur' }),
  new MyError('FIELD_TOO_LONG', { name: 'mot de passe' })
])

console.log(error.json())
/*
sortie:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Échec de la vérification du champ",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"Le champ nom d'utilisateur ne peut pas être vide"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"Le champ mot de passe est trop long"
    }
  ]
}
*/

error.language = 'zh'
console.log(error.json())
/*
sortie:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Échec de la vérification du champ",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"Le champ nom d'utilisateur ne peut pas être vide"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"Le champ mot de passe est trop long"
    }
  ]
}
*/
```

### Combinaison d'erreur standard

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    FIELD_VERIFY_FAILED: 'Échec de la vérification du champ',
    FIELD_CANNOT_EMPTY: 'Le champ {name} ne peut pas être vide',
    FIELD_TOO_LONG: 'Le champ {name} est trop long'
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'nom d'utilisateur' }),
  new MyError('FIELD_TOO_LONG', { name: 'mot de passe' }),
  new Error('Erreur inconnue')
])

console.log(error.json())
/*
sortie:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Échec de la vérification du champ",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"Le champ nom d'utilisateur ne peut pas être vide"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"Le champ mot de passe est trop long"
    },{
      "code":"UNKNOWN_ERROR",
      "message":"Erreur inconnue"
    }
  ]
}
 */
```
