# ошибка

Инструмент [Sumor Cloud](https://sumor.cloud).  
[Больше документации](https://sumor.cloud/error)
Библиотека обработки ошибок поддерживает многоязычность, предварительно заданные коды ошибок и передачу данных.

[![CI](https://github.com/sumor-cloud/error/actions/workflows/ci.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ci.yml)
[![Test](https://github.com/sumor-cloud/error/actions/workflows/ut.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ut.yml)
[![Coverage](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml)
[![Audit](https://github.com/sumor-cloud/error/actions/workflows/audit.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/audit.yml)

## Установка

```bash
npm i @sumor/error --save
```

## Предварительные требования

### Версия Node.JS

Требуется Node.JS версии 18.x или выше

### требуется Node.JS ES модуль

Поскольку эта пакет написан на ES-модуле,
измените следующий код в вашем файле `package.json`:

```json
{
  "type": "module"
}
```

## Использование

### Определение ошибки

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    USER_NOT_FOUND: 'Пользователь не найден',
    USER_EXISTED: 'Пользователь {name} существует'
  }
})

throw new MyError('USER_NOT_FOUND')
// вывод: Ошибка: Пользователь не найден

throw new MyError('USER_EXISTED', { name: 'Алиса' })
// вывод: Ошибка: Пользователь Алиса существует
```

### Многоязычность

```js
import defineError from '@sumor/error'

const MyError = defineError({
  language: 'ru', // язык по умолчанию
  code: {
    USER_NOT_FOUND: 'Пользователь не найден',
    USER_EXISTED: 'Пользователь {name} существует'
  },
  i18n: {
    zh: {
      USER_NOT_FOUND: 'Пользователь не найден',
      USER_EXISTED: 'Пользователь {name} существует'
    }
  }
})

const error = new MyError('USER_EXISTED', { name: 'Алиса' })
error.language = 'ru' // изменить язык ошибки
console.log(error)
// вывод: Ошибка: Пользователь Алиса существует

error.language = 'zh' // изменить язык ошибки
console.log(error)
// вывод: Ошибка: Пользователь Алиса существует
```

### Преобразование ошибки в формат JSON

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    USER_NOT_FOUND: 'Пользователь не найден',
    USER_EXISTED: 'Пользователь {name} существует'
  }
})

const error = new MyError('USER_EXISTED', { name: 'Алиса' })
console.log(error.json())
// вывод: {"code":"USER_EXISTED","message":"Пользователь Алиса существует"}
```

### Внутренняя ошибка

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    FIELD_VERIFY_FAILED: 'Ошибка проверки поля',
    FIELD_CANNOT_EMPTY: 'Поле {name} не может быть пустым',
    FIELD_TOO_LONG: 'Поле {name} слишком длинное'
  },
  i18n: {
    zh: {
      FIELD_VERIFY_FAILED: 'Ошибка проверки поля',
      FIELD_CANNOT_EMPTY: 'Поле {name} не может быть пустым',
      FIELD_TOO_LONG: 'Поле {name} слишком длинное'
    }
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'имя пользователя' }),
  new MyError('FIELD_TOO_LONG', { name: 'пароль' })
])

console.log(error.json())
/* 
вывод: 
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Ошибка проверки поля",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"Поле имя пользователя не может быть пустым"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"Поле пароль слишком длинное"
    }
  ]
}
*/

error.language = 'zh'
console.log(error.json())
/*
вывод:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Ошибка проверки поля",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"Поле имя пользователя не может быть пустым"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"Поле пароль слишком длинное"
    }
  ]
}
*/
```

### Комбинация стандартной ошибки

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    FIELD_VERIFY_FAILED: 'Ошибка проверки поля',
    FIELD_CANNOT_EMPTY: 'Поле {name} не может быть пустым',
    FIELD_TOO_LONG: 'Поле {name} слишком длинное'
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'имя пользователя' }),
  new MyError('FIELD_TOO_LONG', { name: 'пароль' }),
  new Error('Неизвестная ошибка')
])

console.log(error.json())
/*
вывод:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Ошибка проверки поля",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"Поле имя пользователя не может быть пустым"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"Поле пароль слишком длинное"
    },{
      "code":"UNKNOWN_ERROR",
      "message":"Неизвестная ошибка"
    }
  ]
}
 */
```
