# Ошибка

A [Sumor Cloud](https://sumor.cloud) Tool.  
[Больше документации](https://sumor.cloud)
Библиотека обработки ошибок с поддержкой многих языков, предопределенными кодами ошибок и передачей данных.

[![CI](https://github.com/sumor-cloud/error/actions/workflows/ci.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ci.yml)
[![Тест](https://github.com/sumor-cloud/error/actions/workflows/ut.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ut.yml)
[![Покрытие](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml)
[![Аудит](https://github.com/sumor-cloud/error/actions/workflows/audit.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/audit.yml)

## Установка

```bash
npm i @sumor/error --save
```

## Предварительные условия

### Версия Node.JS

Требуется версия Node.JS 16.x или выше

### Требуется Node.JS ES модуль

Поскольку этот пакет написан как ES модуль, пожалуйста, измените следующий код в вашем файле `package.json`:

```json
{
  "type": "module"
}
```

## Использование

### Определение ошибки

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  code: {
    USER_NOT_FOUND: 'Пользователь не найден',
    USER_EXISTED: 'Пользователь {name} существует'
  }
})

throw new MyError('USER_NOT_FOUND')
// вывод: Error: Пользователь не найден

throw new MyError('USER_EXISTED', { name: 'Алиса' })
// вывод: Error: Пользователь Алиса существует
```

### Многие языки

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  language: 'en', // язык по умолчанию
  code: {
    USER_NOT_FOUND: 'Пользователь не найден',
    USER_EXISTED: 'Пользователь {name} существует'
  },
  i18n: {
    zh: {
      USER_NOT_FOUND: 'Пользователь не найден',
      USER_EXISTED: 'Пользователь {name} существует'
    }
  }
})

const error = new MyError('USER_EXISTED', { name: 'Алиса' })
error.language = 'en' // изменить язык ошибки
console.log(error)
// вывод: Error: Пользователь Алиса существует

error.language = 'zh' // изменить язык ошибки
console.log(error)
// вывод: Error: Пользователь Алиса существует
```

### Преобразовать ошибку в JSON

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  code: {
    USER_NOT_FOUND: 'Пользователь не найден',
    USER_EXISTED: 'Пользователь {name} существует'
  }
})

const error = new MyError('USER_EXISTED', { name: 'Алиса' })
console.log(error.json())
// вывод: {"code":"USER_EXISTED","message":"Пользователь Алиса существует"}
```

### Основная ошибка

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  code: {
    FIELD_VERIFY_FAILED: 'Поле проверки не прошло',
    FIELD_CANNOT_EMPTY: 'Поле {name} не может быть пустым',
    FIELD_TOO_LONG: 'Поле {name} слишком длинное'
  },
  i18n: {
    zh: {
      FIELD_VERIFY_FAILED: 'Поле проверки не прошло',
      FIELD_CANNOT_EMPTY: 'Поле {name} не может быть пустым',
      FIELD_TOO_LONG: 'Поле {name} слишком длинное'
    }
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'имя пользователя' }),
  new MyError('FIELD_TOO_LONG', { name: 'пароль' })
])

console.log(error.json())
/* 
вывод: 
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Поле проверки не прошло",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"Поле имя пользователя не может быть пустым"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"Поле пароль слишком длинное"
    }
  ]
}
*/

error.language = 'zh'
console.log(error.json())
/*
вывод:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Поле проверки не прошло",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"Поле имя пользователя не может быть пустым"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"Поле пароль слишком длинное"
    }
  ]
}
*/
```

### Объединение стандартной ошибки

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  code: {
    FIELD_VERIFY_FAILED: 'Поле проверки не прошло',
    FIELD_CANNOT_EMPTY: 'Поле {name} не может быть пустым',
    FIELD_TOO_LONG: 'Поле {name} слишком длинное'
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'имя пользователя' }),
  new MyError('FIELD_TOO_LONG', { name: 'пароль' }),
  new Error('Неизвестная ошибка')
])

console.log(error.json())
/*
вывод:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Поле проверки не прошло",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"Поле имя пользователя не может быть пустым"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"Поле пароль слишком длинное"
    },{
      "code":"UNKNOWN_ERROR",
      "message":"Неизвестная ошибка"
    }
  ]
}
 */
```
