# Ошибка

Инструмент [Sumor Cloud](https://sumor.cloud).  
[Дополнительная документация](https://sumor.cloud) Библиотека обработки ошибок с поддержкой многоязычности, предопределенными кодами ошибок и передачей данных.

[![CI](https://github.com/sumor-cloud/error/actions/workflows/ci.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ci.yml)
[![Test](https://github.com/sumor-cloud/error/actions/workflows/ut.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ut.yml)
[![Покрытие](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml)
[![Аудит](https://github.com/sumor-cloud/error/actions/workflows/audit.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/audit.yml)

## Установка

```bash
npm i @sumor/error --save
```

## Необходимые условия

### Версия Node.JS

Требуется версия Node.JS 16.x или выше.

### Требуется модуль ES в Node.JS

Поскольку этот пакет написан в виде модуля ES, пожалуйста, измените следующий код в вашем файле `package.json`:

```json
{
  "type": "module"
}
```

## Использование

### Определение ошибки

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    USER_NOT_FOUND: 'Пользователь не найден',
    USER_EXISTED: 'Пользователь {name} уже существует'
  }
})

throw new MyError('USER_NOT_FOUND')
// вывод: Ошибка: Пользователь не найден

throw new MyError('USER_EXISTED', { name: 'Алиса' })
// вывод: Ошибка: Пользователь Алиса уже существует
```

### Многоязычность

```js
import defineError from '@sumor/error'

const MyError = defineError({
  language: 'en', // язык по умолчанию
  code: {
    USER_NOT_FOUND: 'Пользователь не найден',
    USER_EXISTED: 'Пользователь {name} уже существует'
  },
  i18n: {
    zh: {
      USER_NOT_FOUND: 'Пользователь не найден',
      USER_EXISTED: 'Пользователь {name} уже существует'
    }
  }
})

const error = new MyError('USER_EXISTED', { name: 'Алиса' })
error.language = 'en' // изменить язык ошибки
console.log(error)
// вывод: Ошибка: Пользователь Алиса уже существует

error.language = 'zh' // изменить язык ошибки
console.log(error)
// вывод: Ошибка: Пользователь Алиса уже существует
```

### Преобразование ошибки в JSON

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    USER_NOT_FOUND: 'Пользователь не найден',
    USER_EXISTED: 'Пользователь {name} уже существует'
  }
})

const error = new MyError('USER_EXISTED', { name: 'Алиса' })
console.log(error.json())
// вывод: {"code":"USER_EXISTED","message":"Пользователь Алиса уже существует"}
```

### Подчиненная ошибка

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    FIELD_VERIFY_FAILED: 'Поле не прошло проверку',
    FIELD_CANNOT_EMPTY: 'Поле {name} не может быть пустым',
    FIELD_TOO_LONG: 'Поле {name} слишком длинное'
  },
  i18n: {
    zh: {
      FIELD_VERIFY_FAILED: 'Поле не прошло проверку',
      FIELD_CANNOT_EMPTY: 'Поле {name} не может быть пустым',
      FIELD_TOO_LONG: 'Поле {name} слишком длинное'
    }
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'имя пользователя' }),
  new MyError('FIELD_TOO_LONG', { name: 'пароль' })
])

console.log(error.json())
/* 
вывод: 
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Поле не прошло проверку",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"Поле имя пользователя не может быть пустым"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"Поле пароль слишком длинное"
    }
  ]
}
*/

error.language = 'zh'
console.log(error.json())
/*
вывод:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Поле не прошло проверку",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"Поле имя пользователя не может быть пустым"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"Поле пароль слишком длинное"
    }
  ]
}
*/
```

### Комбинирование стандартной ошибки

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    FIELD_VERIFY_FAILED: 'Поле не прошло проверку',
    FIELD_CANNOT_EMPTY: 'Поле {name} не может быть пустым',
    FIELD_TOO_LONG: 'Поле {name} слишком длинное'
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'имя пользователя' }),
  new MyError('FIELD_TOO_LONG', { name: 'пароль' }),
  new Error('Неизвестная ошибка')
])

console.log(error.json())
/*
вывод:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Поле не прошло проверку",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"Поле имя пользователя не может быть пустым"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"Поле пароль слишком длинное"
    },{
      "code":"UNKNOWN_ERROR",
      "message":"Неизвестная ошибка"
    }
  ]
}
 */
```
