# Ошибка

Инструмент [Sumor Cloud](https://sumor.cloud).  
[Дополнительная документация](https://sumor.cloud)
Библиотека обработки ошибок поддерживает многоязычность, предопределенные коды ошибок и передачу данных.

[![CI](https://github.com/sumor-cloud/error/actions/workflows/ci.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ci.yml)
[![Test](https://github.com/sumor-cloud/error/actions/workflows/ut.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ut.yml)
[![Coverage](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml)
[![Audit](https://github.com/sumor-cloud/error/actions/workflows/audit.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/audit.yml)

## Установка

```bash
npm i @sumor/error --save
```

## Предварительные требования

### Версия Node.JS

Необходима версия Node.JS 16.x или выше

### Требование к модулю Node.JS ES

Поскольку этот пакет написан на языке ES, пожалуйста, измените следующий код в вашем файле `package.json`:

```json
{
  "type": "module"
}
```

## Использование

### Определение ошибки

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    USER_NOT_FOUND: 'Пользователь не найден',
    USER_EXISTED: 'Пользователь {name} существует'
  }
})

throw new MyError('USER_NOT_FOUND')
// вывод: Error: Пользователь не найден

throw new MyError('USER_EXISTED', { name: 'Alice' })
// вывод: Error: Пользователь Alice существует
```

### Многоязычность

```js
import defineError from '@sumor/error'

const MyError = defineError({
  language: 'en', // язык по умолчанию
  code: {
    USER_NOT_FOUND: 'Пользователь не найден',
    USER_EXISTED: 'Пользователь {name} существует'
  },
  i18n: {
    zh: {
      USER_NOT_FOUND: 'Пользователь не найден',
      USER_EXISTED: 'Пользователь {name} существует'
    }
  }
})

const error = new MyError('USER_EXISTED', { name: 'Alice' })
error.language = 'en' // изменить язык ошибки
console.log(error)
// вывод: Error: Пользователь Alice существует

error.language = 'zh' // изменить язык ошибки
console.log(error)
// вывод: Error: Пользователь Alice существует
```

### Преобразование ошибки в JSON

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    USER_NOT_FOUND: 'Пользователь не найден',
    USER_EXISTED: 'Пользователь {name} существует'
  }
})

const error = new MyError('USER_EXISTED', { name: 'Alice' })
console.log(error.json())
// вывод: {"code":"USER_EXISTED","message":"Пользователь Alice существует"}
```

### Подчиненная ошибка

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    FIELD_VERIFY_FAILED: 'Ошибка проверки поля',
    FIELD_CANNOT_EMPTY: 'Поле {name} не может быть пустым',
    FIELD_TOO_LONG: 'Поле {name} слишком длинное'
  },
  i18n: {
    zh: {
      FIELD_VERIFY_FAILED: 'Ошибка проверки поля',
      FIELD_CANNOT_EMPTY: 'Поле {name} не может быть пустым',
      FIELD_TOO_LONG: 'Поле {name} слишком длинное'
    }
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'username' }),
  new MyError('FIELD_TOO_LONG', { name: 'password' })
])

console.log(error.json())
/* 
вывод: 
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Ошибка проверки поля",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"Поле username не может быть пустым"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"Поле password слишком длинное"
    }
  ]
}
*/

error.language = 'zh'
console.log(error.json())
/*
вывод:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Ошибка проверки поля",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"Поле username не может быть пустым"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"Поле password слишком длинное"
    }
  ]
}
*/
```

### Объединение стандартной ошибки

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    FIELD_VERIFY_FAILED: 'Ошибка проверки поля',
    FIELD_CANNOT_EMPTY: 'Поле {name} не может быть пустым',
    FIELD_TOO_LONG: 'Поле {name} слишком длинное'
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'username' }),
  new MyError('FIELD_TOO_LONG', { name: 'password' }),
  new Error('Неизвестная ошибка')
])

console.log(error.json())
/*
вывод:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Ошибка проверки поля",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"Поле username не может быть пустым"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"Поле password слишком длинное"
    },{
      "code":"UNKNOWN_ERROR",
      "message":"Неизвестная ошибка"
    }
  ]
}
 */
```
