# エラー

[Sumor Cloud](https://sumor.cloud) ツール。  
[さらなるドキュメント](https://sumor.cloud/error)
多言語対応、事前定義されたエラーコード、およびデータの渡し方をサポートするエラーハンドリングライブラリ。

[![CI](https://github.com/sumor-cloud/error/actions/workflows/ci.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ci.yml)
[![Test](https://github.com/sumor-cloud/error/actions/workflows/ut.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ut.yml)
[![Coverage](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml)
[![Audit](https://github.com/sumor-cloud/error/actions/workflows/audit.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/audit.yml)

## インストール

```bash
npm i @sumor/error --save
```

## 前提条件

### Node.JS バージョン

Node.JS バージョン 18.x 以上が必要です

### Node.JS ES モジュールの要求

このパッケージは ES モジュールで書かれているため、`package.json` ファイルの以下のコードを変更してください:

```json
{
  "type": "module"
}
```

## 使用法

### エラーを定義する

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    USER_NOT_FOUND: 'ユーザーが見つかりません',
    USER_EXISTED: 'ユーザー {name} は既に存在します'
  }
})

throw new MyError('USER_NOT_FOUND')
// 出力: Error: ユーザーが見つかりません

throw new MyError('USER_EXISTED', { name: 'Alice' })
// 出力: Error: ユーザー Alice は既に存在します
```

### 多言語対応

```js
import defineError from '@sumor/error'

const MyError = defineError({
  language: 'en', // デフォルト言語
  code: {
    USER_NOT_FOUND: 'ユーザーが見つかりません',
    USER_EXISTED: 'ユーザー {name} は既に存在します'
  },
  i18n: {
    zh: {
      USER_NOT_FOUND: '用户未找到',
      USER_EXISTED: '用户 {name} 已存在'
    }
  }
})

const error = new MyError('USER_EXISTED', { name: 'Alice' })
error.language = 'en' // エラーの言語を変更
console.log(error)
// 出力: Error: ユーザー Alice は既に存在します

error.language = 'zh' // エラーの言語を変更
console.log(error)
// 出力: Error: 用户 Alice 已存在
```

### エラーをJSONに変換する

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    USER_NOT_FOUND: 'ユーザーが見つかりません',
    USER_EXISTED: 'ユーザー {name} は既に存在します'
  }
})

const error = new MyError('USER_EXISTED', { name: 'Alice' })
console.log(error.json())
// 出力: {"code":"USER_EXISTED","message":"ユーザー Alice は既に存在します"}
```

### 内部エラー

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    FIELD_VERIFY_FAILED: 'フィールド検証に失敗しました',
    FIELD_CANNOT_EMPTY: 'フィールド {name} は空にできません',
    FIELD_TOO_LONG: 'フィールド {name} が長すぎます'
  },
  i18n: {
    zh: {
      FIELD_VERIFY_FAILED: '字段验证失败',
      FIELD_CANNOT_EMPTY: '字段 {name} 不能为空',
      FIELD_TOO_LONG: '字段 {name} 过长'
    }
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'ユーザー名' }),
  new MyError('FIELD_TOO_LONG', { name: 'パスワード' })
])

console.log(error.json())
/* 
出力: 
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"フィールド検証に失敗しました",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"フィールド ユーザー名 は空にできません"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"フィールド パスワード が長すぎます"
    }
  ]
}
*/

error.language = 'zh'
console.log(error.json())
/*
出力:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"字段验证失败",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"字段 ユーザー名 不能为空"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"字段 パスワード 过长"
    }
  ]
}
*/
```

### 標準エラーを組み合わせる

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    FIELD_VERIFY_FAILED: 'フィールド検証に失敗しました',
    FIELD_CANNOT_EMPTY: 'フィールド {name} は空にできません',
    FIELD_TOO_LONG: 'フィールド {name} が長すぎます'
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'ユーザー名' }),
  new MyError('FIELD_TOO_LONG', { name: 'パスワード' }),
  new Error('未知のエラー')
])

console.log(error.json())
/*
出力:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"フィールド検証に失敗しました",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"フィールド ユーザー名 は空にできません"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"フィールド パスワード が長すぎます"
    },{
      "code":"UNKNOWN_ERROR",
      "message":"未知のエラー"
    }
  ]
}
 */
```
