# エラー

[Sumor Cloud](https://sumor.cloud) ツール。  
[さらに詳しいドキュメント](https://sumor.cloud)
複数言語をサポートするエラーハンドリングライブラリで、事前に定義されたエラーコードおよびデータの受け渡しをサポートしています。

[![CI](https://github.com/sumor-cloud/error/actions/workflows/ci.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ci.yml)
[![Test](https://github.com/sumor-cloud/error/actions/workflows/ut.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ut.yml)
[![Coverage](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml)
[![Audit](https://github.com/sumor-cloud/error/actions/workflows/audit.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/audit.yml)

## インストール

```bash
npm i @sumor/error --save
```

## 前提条件

### Node.JSのバージョン

Node.JSのバージョン16.x以上が必要です

### Node.JSのESモジュールの使用

このパッケージはESモジュールで記述されているため、`package.json`ファイルの以下のコードを変更してください:

```json
{
  "type": "module"
}
```

## 使用方法

### エラーを定義する

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    USER_NOT_FOUND: 'ユーザーが見つかりません',
    USER_EXISTED: 'ユーザー{name}は既に存在します'
  }
})

throw new MyError('USER_NOT_FOUND')
// 出力: Error: ユーザーが見つかりません

throw new MyError('USER_EXISTED', { name: 'Alice' })
// 出力: Error: ユーザーAliceは既に存在します
```

### 複数言語

```js
import defineError from '@sumor/error'

const MyError = defineError({
  language: 'en', // デフォルト言語
  code: {
    USER_NOT_FOUND: 'ユーザーが見つかりません',
    USER_EXISTED: 'ユーザー{name}は既に存在します'
  },
  i18n: {
    zh: {
      USER_NOT_FOUND: 'ユーザーが見つかりません',
      USER_EXISTED: 'ユーザー{name}は既に存在します'
    }
  }
})

const error = new MyError('USER_EXISTED', { name: 'Alice' })
error.language = 'en' // エラー言語を変更
console.log(error)
// 出力: Error: ユーザーAliceは既に存在します

error.language = 'zh' // エラー言語を変更
console.log(error)
// 出力: Error: ユーザー Alice は既に存在します
```

### エラーをJSONに変換

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    USER_NOT_FOUND: 'ユーザーが見つかりません',
    USER_EXISTED: 'ユーザー{name}は既に存在します'
  }
})

const error = new MyError('USER_EXISTED', { name: 'Alice' })
console.log(error.json())
// 出力: {"code":"USER_EXISTED","message":"ユーザーAliceは既に存在します"}
```

### 根本エラー

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    FIELD_VERIFY_FAILED: 'フィールド検証に失敗しました',
    FIELD_CANNOT_EMPTY: 'フィールド{name}は空にできません',
    FIELD_TOO_LONG: 'フィールド{name}は長すぎます'
  },
  i18n: {
    zh: {
      FIELD_VERIFY_FAILED: 'フィールドの検証に失敗しました',
      FIELD_CANNOT_EMPTY: 'フィールド{name}は空にできませんです',
      FIELD_TOO_LONG: 'フィールド{name}は長すぎます'
    }
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'ユーザ名' }),
  new MyError('FIELD_TOO_LONG', { name: 'パスワード' })
])

console.log(error.json())
/* 
出力: 
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"フィールド検証に失敗しました",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"フィールドユーザ名は空にできません"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"フィールドパスワードは長すぎます"
    }
  ]
}
*/

error.language = 'zh'
console.log(error.json())
/*
出力:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"フィールドの検証に失敗しました",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"フィールドユーザ名は空にできませんです"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"フィールドパスワードは長すぎます"
    }
  ]
}
*/
```

### 標準エラーの組合わせ

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    FIELD_VERIFY_FAILED: 'フィールド検証に失敗しました',
    FIELD_CANNOT_EMPTY: 'フィールド{name}は空にできません',
    FIELD_TOO_LONG: 'フィールド{name}は長すぎます'
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'ユーザ名' }),
  new MyError('FIELD_TOO_LONG', { name: 'パスワード' }),
  new Error('不明なエラー')
])

console.log(error.json())
/*
出力:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"フィールド検証に失敗しました",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"フィールドユーザ名は空にできません"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"フィールドパスワードは長すぎます"
    },{
      "code":"UNKNOWN_ERROR",
      "message":"不明なエラー"
    }
  ]
}
 */
```
